defaults:
  - model: cnn  # Options: cnn, resnet, vit

model_type: ${defaults.0}

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  dataset: "CIFAR10"  # Options: CIFAR10, other datasets
