defaults:
  - model: cnn  # Options: cnn, resnet, vit

model:
  cnn:
    img_size: 224
    num_classes: 10
  resnet:
    img_size: 224
    num_classes: 10
  vit:
    img_size: 224
    patch_size: 16
    num_classes: 10
    emb_size: 768
    depth: 12
    num_heads: 12

training:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  dataset: "CIFAR10"  # Options: CIFAR10, other datasets
