  short_run: true  # Set to true for a short run, false for full dataset
  short_run_percentage: 0.01  # Use 1% of the dataset for short runs
  plot_annotation_distribution: true  # Set to true to visualize annotation distribution
  plot_spatial_distribution: true  # Set to true to visualize spatial distribution
  visualize_frame_sequence: true  # Set to true to visualize frame sequence
  visualize_single_frame: true  # Set to true to visualize a single frame