data_loader:
  video_dir: "./data"  # Relative path to the MOT20 dataset
  
  sequence: train            # Specify 'train' or 'test' sequence
  use_gt: true               # Use ground truth ('gt') annotations if true; otherwise, use 'det' annotations
  batch_size: 4
  seq_len: 8
  num_workers: 4
  transform: null 
