data_loader:
  video_dir: "/mnt/c/open_source/DeepLearningProjects/data/MOT20/train"
  annotation_dir: "/mnt/c/open_source/DeepLearningProjects/data/MOT20/MOT20/train/annotations"
  batch_size: 4
  seq_len: 8
  num_workers: 4
